Title:

Tactical Design by Example - Using Kotlin and Spring Boot (Part 11) - Improving Command factories with Kotlin's Result type

----

Description:

Tactical Design by Example - Using Kotlin and Spring Boot (Part 11) - Improving Command factories with Kotlin's Result type

----

Date:

11/23/2020

----

Tags:

ddd, kotlin, hexagon architecture, spring boot, event storming, command, policy, application service

----

Text:

Only recently have I come across the _Result_ type in Kotlin's standard library. It's been added in version 1.3. It's a great way to implement a simple _Either_-like type, something I have mentioned in the previous week.

## Return nullable type or Result?

I built a factory method for a command that returned a nullable type

```kotlin
data class UpdateDepositPrice(
    val articleId: String,
    val refundPrice: Int,
    val currency: Currency,
    val currencyUnit: CurrencyUnit
) : Command() {
    companion object {
        operator fun invoke(priceUpdated: PriceUpdated): UpdateDepositPrice? =
            priceUpdated.getArticleId()?.let { articleId ->
                UpdateDepositPrice(
                    articleId,
                    priceUpdated.price.customAttributes.refund,
                    Currency.valueOf(priceUpdated.price.currency),
                    CurrencyUnit.valueOf(priceUpdated.price.unit)
                )
            }
    }
}
```

Problem is, I now pass no error message back to the caller, and I have to log a generic error message.

```kotlin
UpdateDepositPrice(priceUpdated)?.also {
    workflow.process(it)
} ?: log.warn("generic error message")
```

### Enter the Result type

Let's rewrite the factory method with the _Result_ type

```kotlin
operator fun invoke(priceUpdated: PriceUpdated): Result<UpdateDepositPrice> =
    priceUpdated.getArticleId()?.let { articleId ->
        Result.success(
            UpdateDepositPrice(
                articleId,
                priceUpdated.price.customAttributes.refund,
                Currency.valueOf(priceUpdated.price.currency),
                CurrencyUnit.valueOf(priceUpdated.price.unit)
            )
        )
    } ?: Result.failure(
        IllegalArgumentException("No article id found in listing!")
    )
```

This adds a minimal wrapper around the returned command, plus an exception in case the articleId is null. The exception is not thrown!

## Handling the result

There are various options here, I have tried the following

### fold

_Fold_ takes two lambdas as arguments. It is short, but the term "folding" is a bit too technical for my taste

```kotlin
UpdateDepositPrice(priceUpdated).fold({
    workflow.process(it)
}, { e ->
    log.warn(e.message)
})
```

### onSuccess, onFailure

Even though this is a little longer, I think this is much more readable, especially if you are not aware of the _Result_ type

```kotlin
UpdateDepositPrice(priceUpdated)
    .onSuccess {
        workflow.process(it)
    }.onFailure { e ->
        log.warn(e.message)
    }
```

Both are valid options. You can also go for _getOrElse_ or _getOrDefault_, read more about the _Result_ type in the (link:https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result/ text:Kotlin documentation).

## One minor drawback though

Returning _Result_ types is still an experimental feature, so use it at your own risk. You need to activate it via the compiler flag

```
-Xallow-result-return-type
```

Thanks to (link:https://twitter.com/pysaumont text:Pierre-Yves Saumont) for mentioning the Result type in his book (link:https://www.manning.com/books/the-joy-of-kotlin text:The Joy of Kotlin). Very helpful!

Go back to (link:blog/tactical-design-by-example-using-kotlin-and-spring-boot-part-10-creating-commands-with-kotlins-invoke-function text:part ten).




